name: Find-change-module
on:
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.find-modules.outputs.matrix}}
      image-tag: ${{steps.shorten-commit.outputs.sha_short}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set changed modules as matrix
        id: set-matrix
        run: |
          modules=$(./bin/find_changed_modules.sh)
          echo "matrix=[\"${modules//', '/\",\"}\"]" >> $GITHUB_OUTPUT
      - name: Shorten commit hash
        id: shorten-commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: "${{needs.job1.outputs.matrix}}"
    steps: 
      - name: print image tag
        run: |
          echo "${{needs.job1.outputs.image-tag}}"
      
