name: Find-change-module
on:
  push:
    branches:
      - "main"
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    outputs:
      changed-modules: steps.find-modules.outputs.modules
      image-tag: steps.shorten-commit.outputs.sha_short
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Find changed modules
        id: find-modules
        run: ./bin/find_changed_modules.sh
      - name: Shorten commit hash
        id: shorten-commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  print-output:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo ${{needs.build-and-upload.outputs.changed_modules}}
          echo ${{needs.build-and-upload.outputs.image-tag}}
        
      
