name: Find-change-module
on:
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      changed-modules: steps.find-modules.outputs.modules
      image-tag: steps.shorten-commit.outputs.sha_short
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find changed modules
        id: find-modules
        run: bash ./bin/find_changed_modules.sh >> $GITHUB_OUTPUT
      - name: Shorten commit hash
        id: shorten-commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: Shorten commit hash
        id: shorten-commit
        run: |
          echo "${{needs.job1.outputs.changed_modules}}"
          echo "${{needs.job1.outputs.image-tag}}"
  job3:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
    - run: echo ${{needs.job3.outputs.output1}} ${{needs.job3.outputs.output2}}
        
      
