name: Find-change-module
on:
  push:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
      image-tag: ${{steps.shorten-commit.outputs.sha_short}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set changed modules as matrix
        id: set-matrix
        run: |
          echo "matrix=[\"${$(./bin/find_changed_modules.sh)//', '/\",\"}\"]" >> $GITHUB_OUTPUT
      - name: Shorten commit hash
        id: shorten-commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo ${{steps.set-matrix.outputs.matrix}}
          echo ${{steps.shorten-commit.outputs.sha_short}}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        module: ${{fromJson(needs.job1.outputs.matrix)}}
    steps: 
      - name: print image tag
        run: |
          echo "${{needs.job1.outputs.image-tag}}"