name: New Staging Deployment
on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to deploy"
        required: true
        type: choice
        options:
          - webhook
      environment:
        description: "Environment to deploy the image to"
        required: true
        type: choice
        options:
          - staging
      tag:
        description: Image to deploy
        required: true

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # Log in to Amazon ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          aws-region: ap-southeast-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install serverless
        run: npm i -g serverless
      - name: Install dependencies for serverless framework # This is temporary until I figure out how to remove serverless plugin when deploying
        run: yarn install
      - name: Deploy
        run: make deploy MODULE=${{ github.event.inputs.module }} BUILD=${{ github.event.inputs.tag }} STAGE=${{ github.event.inputs.environment }}
